#pragma config(Sensor, S3,     GoalBaseTouch,  sensorTouch)
#pragma config(Sensor, S4,     ColorSensor,    sensorColorNxtFULL)
//*!!Code automatically generated by K^3S^3T               !!*//

task main()
{
	while(true)
	{
		if(SensorValue[GoalBaseTouch] != 0)
		{
			SensorType[ColorSensor] = sensorColorNxtGREEN;
		}
		else
		{
			SensorType[ColorSensor] = sensorColorNxtNONE;
		}
	}
}
