#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     LiftLimitTouch, sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheels,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Spindle,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheels,   tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    Hooks,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    Gate,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool hasErrors = false;

	nMotorEncoder[LeftWheels] = 0;
	nMotorEncoder[RightWheels] = 0;
	nMotorEncoder[Lift] = 0;

	eraseDisplay();

	// test motors

	// test LeftWheels

	motor[LeftWheels] = 20;
	displayTextLine(1, "Testing Left Wheels");
	wait1Msec(500);
	motor[LeftWheels] = 0;

	if (nMotorEncoder[LeftWheels] == 0)
	{
		// either motor or encoder is faulty

		hasErrors = true;
		displayTextLine(2, "Left wheels error");
		playTone(100, 5);
		wait1Msec(2000);
	}
	eraseDisplay();

	// test RightWheels

	motor[RightWheels] = 20;
	displayTextLine(1, "Testing Right Wheels");
	wait1Msec(500);
	motor[RightWheels] = 0;

	if (nMotorEncoder[RightWheels] == 0)
	{
		// either motor or encoder is faulty

		hasErrors = true;
		displayTextLine(2, "Right wheels error");
		playTone(500, 5);
		wait1Msec(2000);
	}
	eraseDisplay();

	motor[Lift] = 20;
	displayTextLine(1, "Testing Lift");
	wait1Msec(500);
	motor[Lift] = 0;

	if (nMotorEncoder[Lift] == 0)
	{
		// either motor or encoder is faulty

		hasErrors = true;
		displayTextLine(2, "Lift error");
		playTone(1000, 5);
		wait1Msec(2000);
	}
	else
	{
		motor[Lift] = -20;
		wait1Msec(500);
		motor[Lift] = 0;
		wait1Msec(2000);
	}
	eraseDisplay();

	// test Spindle

	motor[Spindle] = 20;
	wait1Msec(500);
	motor[Spindle] = 0;

	// test Hooks

	servo[Hooks] = 180;
	wait1Msec(1000);
	servo[Hooks] = 10;
	wait1Msec(1000);

	// test Gate

	servo[Gate] = 50;
	wait1Msec(1000);
	servo[Gate] = 70;
	wait1Msec(1000);

	// play tone to signal end of program
	if(!hasErrors)
	{
		displayTextLine(4, "No errors.");
	}


	playTone(3000, 5);
	wait1Msec(5000);

}
