#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     LiftLimitTouch, sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheels,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Spindle,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheels,   tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    Hooks,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    Gate,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Touch Sensor Values (may need to change)
#define TOUCH_SENSOR_PRESSED 1
#define TOUCH_SENSOR_NOT_PRESSED 0

/*
 1. Check Primary Battery and External Battery Voltage (We know it can be done because these are shown during the run.
 2. Check DC Motors. Check Encoders.
 3. Check Servo Motors. Check Servo Position Change.
 4. Check Touch Sensor (wait for it to be pressed and confirm).
 5. Check Spindle turn.
*/

task main()
{
	bool hasErrors = false;
	/*bool leftWheelsError = false;
	bool rightWheelsError = false;
	bool liftError = false;
	bool spindleError = false;
	bool hooksError = false;
	bool gateError = false;
	bool touchSensorError = false;*/

	nMotorEncoder[LeftWheels] = 0;
	nMotorEncoder[RightWheels] = 0;
	nMotorEncoder[Lift] = 0;

	eraseDisplay();

	// test motors

	// test LeftWheels

	displayTextLine(1, "Current Battery Level:%f", nImmediateBatteryLevel); //in millivolts
	displayTextLine(2, "External Battery Voltage:%f", externalBattery);
	wait1Msec(500);

	eraseDisplay();

	motor[LeftWheels] = 20;
	displayTextLine(1, "Testing Left Wheels");
	wait1Msec(500);
	motor[LeftWheels] = 0;

	if(nMotorEncoder[LeftWheels] == 0)
	{
		// either motor or encoder is faulty

		hasErrors = true;
		//leftWheelsError = true;
		displayTextLine(2, "Left wheels error");
		playTone(100, 5);
		wait1Msec(2000);
	}


	eraseDisplay();

	// test RightWheels

	motor[RightWheels] = 20;
	displayTextLine(1, "Testing Right Wheels");
	wait1Msec(500);
	motor[RightWheels] = 0;

	if (nMotorEncoder[RightWheels] == 0)
	{
		// either motor or encoder is faulty

		hasErrors = true;
		//rightWheelsError = true;
		displayTextLine(2, "Right wheels error");
		playTone(500, 5);
		wait1Msec(2000);
	}

	eraseDisplay();

	motor[Lift] = 20;
	displayTextLine(1, "Testing Lift");
	wait1Msec(500);
	motor[Lift] = 0;

	if (nMotorEncoder[Lift] == 0)
	{
		// either motor or encoder is faulty

		hasErrors = true;
		//liftError = true;
		displayTextLine(2, "Lift error");
		playTone(1000, 5);
		wait1Msec(2000);
	}
	else
	{
		motor[Lift] = -20;
		wait1Msec(500);
		motor[Lift] = 0;
		wait1Msec(2000);
	}

	eraseDisplay();

	// test Spindle

	motor[Spindle] = 20;
	displayTextLine(1, "Testing Spindle");
	wait1Msec(500);
	motor[Spindle] = 0;

	if(motor[Spindle] == 0)
	{
		// either motor or encoder is faulty

		hasErrors = true;
		//spindleError = true;
		displayTextLine(2, "Spindle error");
		playTone(1000, 5);
		wait1Msec(2000);
	}
	else
	{
		motor[Spindle] = -20;
		wait1Msec(500);
		motor[Spindle] = 0;
		wait1Msec(2000);
	}

	eraseDisplay();

	// test Hooks

	servo[Hooks] = 180;
	displayTextLine(1, "Testing Hooks");
	wait1Msec(1000);

	if(servo[Hooks] == 0) //current servo position
	{
		hasErrors = true;
		//hooksError = true;
		displayTextLine(2, "Hooks error");
		playTone(600, 5);
		wait1Msec(2000);
	}
	else
	{
		servo[Hooks] = 10;
		wait1Msec(2000);
	}

	eraseDisplay();

	// test Gate

	displayTextLine(1, "Testing Gate");
	servo[Gate] = 50;
	wait1Msec(1000);

	if(servo[Gate] == 0)
	{
		hasErrors = true;
		//gateError = true;
		displayTextLine(2, "Gate errors");
		playTone(700, 5);
		wait1Msec(2000);
	}
	else
	{
		servo[Gate] = 70;
		wait1Msec(1000);
	}

	eraseDisplay();

	while(SensorValue[LiftLimitTouch] == TOUCH_SENSOR_NOT_PRESSED)
	{
		motor[Lift] = 20;
		displayTextLine(1, "Testing Touch Sensor");
	}
	if(SensorValue[LiftLimitTouch] == TOUCH_SENSOR_PRESSED)
	{
		displayTextLine(2, "Touch sensor pressed");
		motor[Lift] = -20;
		wait1Msec(2000);
	}
	else
	{
		hasErrors = true;
		//touchSensorError = true;
		displayTextLine(2, "Touch sensor error");
		wait1Msec(2000);
	}

	eraseDisplay();

	// play tone to signal end of program
	if(!hasErrors)
	{
		displayTextLine(4, "No errors.");
	}



	playTone(3000, 5);
	wait1Msec(5000);

}
