#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheels,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Spindle,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheels,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    Gate,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DIAMETER 3
#define TRACK_DISTANCE 15.5
#define CLOCKWISE true
#define COUNTER_CLOCKWISE false

void dualMotorTurn(float robotDegrees, float power, bool direction);

task main()
{
	dualMotorTurn(90, 30, COUNTER_CLOCKWISE);
	wait1Msec(10000);
	dualMotorTurn(180, 30, CLOCKWISE);
}

void dualMotorTurn(float robotDegrees, float power, bool direction) //robot turns using both motors
{
	int encoderCounts = TRACK_DISTANCE/DIAMETER*(robotDegrees*4);
	nMotorEncoder[LeftWheels] = 0;
	nMotorEncoder[RightWheels] = 0;
	if (direction == CLOCKWISE)												//turn robot clockwise or counter-clockwise, depending on user input
	{
		nMotorEncoderTarget[LeftWheels] = encoderCounts;
		nMotorEncoderTarget[RightWheels] = -1*encoderCounts;
		motor[LeftWheels] = power;
		motor[RightWheels] = -1 * power;
		while((nMotorEncoder[LeftWheels] < encoderCounts) || (nMotorEncoder[RightWheels] > -1*encoderCounts))
		{
			// idle loop
		}
	}
	else
	{
		nMotorEncoderTarget[LeftWheels] = -1*encoderCounts;
		nMotorEncoderTarget[RightWheels] = encoderCounts;
		motor[LeftWheels] = -1* power;
		motor[RightWheels] = power;
		while((nMotorEncoder[LeftWheels] > -1*encoderCounts) || (nMotorEncoder[RightWheels] < encoderCounts))
		{
			// idle loop
		}
	}
	motor[LeftWheels] = 0;
	motor[RightWheels] = 0;
}
