#pragma config(Sensor, S3,     ColorSensor,    sensorColorNxtFULL)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Servo,  srvo_S1_C3_5,    Hooks,                tServoStandard)
//*!!Code automatically generated by K^3S^3T Hogwarts wizards               !!*//

#include "hitechnic-sensormux.h" // For Multiplexer
#include "lego-touch.h" // For touch sensors in Multiplexer

// For use of Multiplexer
const tMUXSensor GoalBaseTouch1 = msensor_S4_1;
const tMUXSensor GoalBaseTouch2 = msensor_S4_2;

task main()
{
	if((TSreadState(GoalBaseTouch1) != 0)||(TSreadState(GoalBaseTouch2)))
	{ // If at least one touch sensor is pressed
		if(ServoValue[Hooks] > 100)
		{
			// Turns green if hooks is down and goal base touch is detected
			SensorType[ColorSensor] = sensorColorNxtGREEN;
		}
		else
		{
			// Turns blue if only goal base touch is detected
			SensorType[ColorSensor] = sensorColorNxtBLUE;
		}
	}
	else if(ServoValue[Hooks] > 100) // Turns red if hooks is down
	{
		SensorType[ColorSensor] = sensorColorNxtRED;
	}
	else
	{
		SensorType[ColorSensor] = sensorColorNxtNONE; // Emits no light
	}
}
