#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Servo,  srvo_S1_C3_5,    Hooks,                tServoStandard)
//*!!Code automatically generated by K^3S^3T Hogwarts wizards               !!*//

#define GOAL_HOOKS_OPEN 10
#define GOAL_HOOKS_CLOSED 185
#define WAIT_TIME 10000

task main()
{
	servo[Hooks] = GOAL_HOOKS_OPEN;
	wait1Msec(2000);
	servo[Hooks] = GOAL_HOOKS_CLOSED;
	wait1Msec(WAIT_TIME);
	servo[Hooks] = GOAL_HOOKS_OPEN;
	wait1Msec(2000);
}
