#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by K^3S^3T Hogwarts wizards               !!*//

//		Manually raises or lowers lift

//definitions that help readability of the program

task ShowLiftEncoderValues();

task main()
{
	startTask(ShowLiftEncoderValues);

	while(true)
	{
		if(nNxtButtonPressed == 1)	// raises lift
		{
			motor[Lift] = 25;
		}
		if(nNxtButtonPressed == 2)	//lowers lift
		{
			motor[Lift] = -25;
		}
		if(nNxtButtonPressed == 3)	//stops lift
		{
			motor[Lift] = 0;
		}
	} //while(true)
} //main()

task ShowLiftEncoderValues()
{
	eraseDisplay();
	nMotorEncoder[Lift] = 0;

	while(true)
	{
		displayBigTextLine(2, "%d",nMotorEncoder[Lift]);
	}	//while(true)
}	//ShowLiftEncoderValues()
