#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheels,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Spindle,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheels,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    Gate,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//definitions that help readability of the program

#define GATE_CLOSED 150
#define GATE_OPEN 30
#define LIFT_LIMIT 1440*11  //11 rotations of the motor (arbitrary test)


enum SpindleStateEnumeration {Running,Stopped};
enum LiftStateEnumeration  {Running, Stopped};

SpindleStateEnumeration SpindleState;
LiftStateEnumeration LiftState;

task ShowLiftEncoderValues();

task main()
{
	startTask(ShowLiftEncoderValues);
	while(true){
		if(nNxtButtonPressed==1){
			motor[Lift]=25;
		}
		if(nNxtButtonPressed==2){
			motor[Lift]=-25;
		}
		if(nNxtButtonPressed==3){
			motor[Lift]=0;
		}
	}

}

task ShowLiftEncoderValues()
{
	eraseDisplay();
	//initialize Encoder;

	nMotorEncoder[Lift]=0;
	while(1){
		displayBigTextLine(2,"%d",nMotorEncoder[Lift]);
	}
}
