#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheels,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Spindle,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheels,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    Gate,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

// IMPORTANT: ANY VARIABLES/CONSTANTS WITH THE CONSTANT "FOO" MUST BE MEASURED AND CHANGED
#define FOO 0

// Made these new button names so they are easier to understand. You won't have to type the whole thing because of auto-complete.

// Controller 1 Buttons
#define CTRL1_BUTTON_LEFT joy1Btn(1)
#define CTRL1_BUTTON_BOTTOM joy1Btn(2)
#define CTRL1_BUTTON_TOP joy1Btn(3)
#define CTRL1_BUTTON_RIGHT joy1Btn(4)
#define BTN_ROTATESPINDLE_FORWARD joy1Btn(7)
#define BTN_ROTATESPINDLE_BACKWARD joy1Btn(8)
#define BTN_GRAB_GOALBASE FOO
// Controller 2 Buttons
#define BTN_LIFT_LOWERGOAL joy2Btn(1)
#define BTN_LIFT_BASE joy2Btn(2)
#define BTN_LIFT_TOPGOAL joy2Btn(3)
#define BTN_LIFT_MIDDLEGOAL joy2Btn(4)
#define BTN_GATE_CTRL joy2Btn(6)
//#define BTN_GATE_CLOSED joy2Btn (5)
#define BTN_LIFT_UP joy2Btn(11)
#define BTN_LIFT_DOWN joy2Btn(12)

// Controller 1 Joysticks
#define CTRL1_JOY_LEFT_X joystick.joy1_x1
#define CTRL1_JOY_LEFT_Y joystick.joy1_y1
#define CTRL1_JOY_RIGHT_X joystick.joy1_x2
#define CTRL1_JOY_RIGHT_Y joystick.joy1_y2
// Controller 2 Joysticks
#define CTRL2_JOY_LEFT_X joystick.joy2_x1
#define CTRL2_JOY_LEFT_Y joystick.joy2_y1
#define CTRL2_JOY_RIGHT_X joystick.joy2_x2
#define CTRL2_JOY_RIGHT_Y	joystick.joy2_y2

// Controllers' D-Pads.
#define CTRL1_DPAD joystick.joy1_TopHat
#define DPAD_TOP 0
#define DPAD_TOP_RIGHT 1
#define DPAD_RIGHT 2
#define DPAD_BOTTOM_RIGHT 3
#define DPAD_BOTTOM 4
#define DPAD_BOTTOM_LEFT 5
#define DPAD_LEFT 6
#define DPAD_TOP_LEFT 7

// Lift
#define LIFT_MAX 22300
#define LIFT_TOP 22250
#define LIFT_MIDDLE 14350
#define LIFT_LOWER 7150
#define LIFT_BASE 0

//Gate
#define GATE_CLOSED 50
#define GATE_OPEN 150

enum SpindleStateEnum {Running, Stopped};
enum LiftStateEnum {Running, Stopped};
enum GateStateEnum {Open, Closed};

SpindleStateEnum SpindleState;
LiftStateEnum LiftState;
GateStateEnum GateState;

// Primary functions/tasks
void initializeRobot();
void clrTimers();
task liftCheckMAX(); // Checks if the lift is too high
task liftCheckMIN();
void wheelsMove();
void buttonFunctions(); // Has uses for buttons
// Secondary functions
void liftOverride();
void spindleMove();
void gateControl();
void liftReach();
void grabBase();
// Tertiary functions
void moveLift(int encoderCounts);

task main()
{
	initializeRobot();
	waitForStart();

	startTask (liftCheckMAX);
	startTask (liftCheckMIN);
	clrTimers();

	while (1)
	{
		getJoystickSettings(joystick);
		wheelsMove();
		buttonFunctions();
	}
}

void initializeRobot ()
{
	LiftState=Stopped;
	servo[Gate]= GATE_CLOSED;
	GateState=Closed;
	SpindleState= Stopped;

}

void clrTimers()
{
	clearTimer (T1);	//timer used for Spindle
	clearTimer (T2);	//timer used for Lift
	clearTimer (T3);	//timer used for Gate
}

task liftCheckMAX ()
{
	if (nMotorEncoder[Lift] > LIFT_MAX)
	{
		while (nMotorEncoder[Lift] > LIFT_MAX)
			motor[Lift] = -20; // Might have to change values...
		motor[Lift] = 0;
	}
}

task liftCheckMIN ()
{
	if (nMotorEncoder[Lift] < LIFT_BASE)
	{
		while (nMotorEncoder[Lift] < LIFT_BASE)
			motor[Lift] = 20; // Might have to change values...
		motor[Lift] = 0;
	}
}

void wheelsMove ()
{
	switch (CTRL1_DPAD)
	{
	case DPAD_TOP:
		motor[LeftWheels] = 45;
		motor[RightWheels] = 45;
		break;
	case DPAD_BOTTOM:
		motor[LeftWheels] = -40;
		motor[RightWheels] = -40;
		break;
	case DPAD_RIGHT:
		motor[LeftWheels] = 60;
		motor[RightWheels] = -60;
		break;
	case DPAD_LEFT:
		motor[LeftWheels] = -60;
		motor[RightWheels] = 60;
		break;
	case DPAD_TOP_RIGHT:
		motor[LeftWheels] = 50;
		motor[RightWheels] = 0;
		break;
	case DPAD_BOTTOM_RIGHT:
		motor[LeftWheels] = -50;
		motor[RightWheels] = 0;
		break;
	case DPAD_BOTTOM_LEFT:
		motor[LeftWheels] = 0;
		motor[RightWheels] = -50;
		break;
	case DPAD_TOP_LEFT:
		motor[LeftWheels] = 0;
		motor[RightWheels] = 50;
		break;
	default:
		motor[LeftWheels] = CTRL1_JOY_LEFT_Y / 127 * 100; // Scales joystick values for motors.
		motor[RightWheels] = CTRL1_JOY_RIGHT_Y / 127 * 100;
		break;
	}
}

void buttonFunctions()
{
	liftOverride();
	spindleMove();
	gateControl();
	liftReach();
	grabBase();
}

void liftOverride()
{
	if(BTN_LIFT_UP)
	{
		if(time1(T2)>500) 	//checks to see if button isn't pressed to fast
		{
			if(LiftState== Stopped)
			{
				motor[Lift]= 70;
				LiftState= Running;
			}
			else
			{
				motor[Lift]= 0;
				LiftState= Stopped;
			}
			clearTimer(T2);
		}
	}

	if(BTN_LIFT_DOWN)
	{
		if(time1(T2)>500) 	//checks to see if button isn't pressed to fast
		{
			if(LiftState== Stopped)
			{
				motor[Lift]= -70;
				LiftState= Running;
			}
			else
			{
				motor[Lift]= 0;
				LiftState= Stopped;
			}
			clearTimer(T2);
		}
	}
}

void spindleMove()
{
	if(BTN_ROTATESPINDLE_FORWARD)
	{
		if(time1(T1)>500)		//checks to see if button isn't pressed to fast
		{
			if(SpindleState== Stopped)
			{
				motor[Spindle]=100;		//starts the Spindle
				SpindleState= Running;
			}
			else
			{
				motor[Spindle]=0;		//stops the Spindle
				SpindleState=Stopped;
			}
			clearTimer(T1);
		}
	}
	if(BTN_ROTATESPINDLE_BACKWARD)
	{
		if(time1(T1)>500)	//checks to see if button isn't pressed to fast
		{
			if(SpindleState== Stopped)
			{
				motor[Spindle]=-100;		//starts the spindle (backwards)
				SpindleState= Running;
			}
			else
			{
				motor[Spindle]=0;		//stops the spindle
				SpindleState=Stopped;
			}
			clearTimer(T1);
		}
	}
}

void gateControl()
{
	if(BTN_GATE_CTRL)
	{
		if(time1(T3)>500)	//checks to see if button is pressed too fast
		{
			if(GateState== Closed)
			{
				servo[Gate]= GATE_OPEN;	//opens gate
				GateState=Open;
			}
			else
			{
				servo[Gate]=GATE_CLOSED;	//closes gate
				GateState=Closed;
			}
			clearTimer(T3);

		}

		/*	servo[Gate]= GATE_OPEN;
		}

		if (BTN_GATE_CLOSED)
		{
		servo[Gate]= GATE_CLOSED;
		}*/

	}
}

void liftReach()
{
	if(BTN_LIFT_BASE)
	{
		moveLift(LIFT_BASE);
	}

	if(BTN_LIFT_LOWERGOAL)
	{
		moveLift(LIFT_LOWER);
	}

	if(BTN_LIFT_MIDDLEGOAL)
	{
		moveLift(LIFT_MIDDLE);
	}

	if(BTN_LIFT_TOPGOAL)
	{
		moveLift(LIFT_TOP);
	}
}

void grabBase()
{
	if(BTN_GRAB_GOALBASE)
	{
		//blank for now
	}
}

void moveLift(int encoderCounts)
{
	if(nMotorEncoder[Lift]>encoderCounts)
	{
		LiftState= Running;
		motor[Lift]= -65;
		while((nMotorEncoder[Lift]>encoderCounts)&&(nMotorEncoder[Lift]>LIFT_LOWER))
		{
			//idle loop
		}

		if(nMotorEncoder[Lift]>encoderCounts)
		{
			motor[Lift]=-30;
			while(nMotorEncoder[Lift]>encoderCounts)
			{
				//idle
			}
		}
	}
	else if(nMotorEncoder[Lift]<encoderCounts)
	{
		motor[Lift]= 80;
		LiftState= Running;
		while(nMotorEncoder[Lift]<encoderCounts)
		{
			//idle
		}
	}

	motor[Lift]=0;
	LiftState=Stopped;
}
