#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheels,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Spindle,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheels,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    Gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    Gate,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

// IMPORTANT: ANY VARIABLES/CONSTANTS WITH THE CONSTANT "FOO" MUST BE MEASURED AND CHANGED
#define FOO 0

// Made these new button names so they are easier to understand. You won't have to type the whole thing because of auto-complete.

// Controller 1 Buttons
#define CTRL1_BUTTON_LEFT joy1Btn(1)
#define CTRL1_BUTTON_BOTTOM joy1Btn(2)
#define CTRL1_BUTTON_TOP joy1Btn(3)
#define CTRL1_BUTTON_RIGHT joy1Btn(4)
#define BTN_ROTATESPINDLE_FORWARD joy1Btn(7)
#define BTN_ROTATESPINDLE_BACKWARD joy1Btn(8)
#define BTN_GRAB_GOALBASE FOO
// Controller 2 Buttons
#define BTN_LIFT_LOWERGOAL joy2Btn(1)
#define BTN_LIFT_BASE joy2Btn(2)
#define BTN_LIFT_TOPGOAL joy2Btn(3)
#define BTN_LIFT_MIDDLEGOAL joy2Btn(4)
#define BTN_GATE_CTRL joy1Btn(6)
#define BTN_LIFT_UP joy1Btn(11)
#define BTN_LIFT_DOWN joy1Btn(12)

// Controller 1 Joysticks
#define CTRL1_JOY_LEFT_X joystick.joy1_x1
#define CTRL1_JOY_LEFT_Y joystick.joy1_y1
#define CTRL1_JOY_RIGHT_X joystick.joy1_x2
#define CTRL1_JOY_RIGHT_Y joystick.joy1_y2
// Controller 2 Joysticks
#define CTRL2_JOY_LEFT_X joystick.joy2_x1
#define CTRL2_JOY_LEFT_Y joystick.joy2_y1
#define CTRL2_JOY_RIGHT_X joystick.joy2_x2
#define CTRL2_JOY_RIGHT_Y	joystick.joy2_y2

// Controllers' D-Pads. IDEA FOR D-PAD: USE RIGHT AND LEFT BUTTONS FOR SPINNING.
#define CTRL1_DPAD joystick.joy1_TopHat
#define CTRL2_DPAD joystick.joy2_TopHat
#define DPAD_LEFT 6
#define DPAD_RIGHT 2

// Lift
#define LIFT_MAX 22300
#define LIFT_TOP 22250
#define LIFT_MIDDLE 14350
#define LIFT_LOWER 7150
#define LIFT_BASE 0

//Gate
#define GATE_CLOSED 50
#define GATE_OPEN 150

enum SpindleStateEnum {Running, Stopped};
enum LiftStateEnum {Running, Stopped};
enum GateStateEnum {Open, Closed};

SpindleStateEnum SpindleState;
LiftStateEnum LiftState;
GateStateEnum GateState;

// Primary functions/tasks
void initializeRobot(void);
task liftCheckMAX (); // Checks if the lift is too high
task liftCheckMIN ();
void wheelsMove(void);
void moveLift(int encoderCounts);
void buttonFunctions();

task main()
{
	initializeRobot();
	waitForStart();

	startTask (liftCheckMAX);
	startTask (liftCheckMIN);

	clearTimer (T1);	//timer used for Spindle
	clearTimer (T2);	//timer used for Lift
	clearTimer (T3);	//timer used for Gate

	while (1)
	{
		getJoystickSettings(joystick);
		wheelsMove();
		buttonFunctions();
	}
}

void initializeRobot (void)
{
	// empty for now
}

task liftCheckMAX () {
	if (nMotorEncoder[Lift] > LIFT_MAX)
	{
		while (nMotorEncoder[Lift] > LIFT_MAX)
			motor[Lift] = -20; // Might have to change values...
		motor[Lift] = 0;
	}
}

task liftCheckMIN () {
	if (nMotorEncoder[Lift] < LIFT_BASE)
	{
		while (nMotorEncoder[Lift] < LIFT_BASE)
			motor[Lift] = 20; // Might have to change values...
		motor[Lift] = 0;
	}
}

void wheelsMove (void)
{
	if (CTRL1_DPAD == DPAD_RIGHT) // Spins robot to the right
	{
		motor[LeftWheels] = 30; // Might have to change values...
		motor[RightWheels] = -30;
	}
	else if (CTRL1_DPAD == DPAD_LEFT) // Spins robot to the left
	{
		motor[LeftWheels] = -30;
		motor[RightWheels] = 30;
	}
	else // If there is no input from the D-Pad, use joysticks
	{
		motor[LeftWheels] = CTRL1_JOY_LEFT_Y / 127 * 100; // Scales joystick values for motors.
		motor[RightWheels] = CTRL1_JOY_RIGHT_Y / 127 * 100;
	}
}

void buttonFunctions()
{
	if(BTN_LIFT_UP)
	{
		if(time1(T2)>500) 	//checks to see if button isn't pressed to fast
		{
			if(LiftState== Stopped)
			{
				motor[Lift]= 70;
				LiftState= Running;
			}
			else
			{
				motor[Lift]= 0;
				LiftState= Stopped;
			}
			clearTimer(T2);
		}
	}

	if(BTN_LIFT_DOWN)
	{
		if(time1(T2)>500) 	//checks to see if button isn't pressed to fast
		{
			if(LiftState== Stopped)
			{
				motor[Lift]= -70;
				LiftState= Running;
			}
			else
			{
				motor[Lift]= 0;
				LiftState= Stopped;
			}
			clearTimer(T2);
		}
	}

	if(BTN_ROTATESPINDLE_FORWARD)
	{
		if(time1(T1)>500)		//checks to see if button isn't pressed to fast
		{
			if(SpindleState== Stopped)
			{
				motor[Spindle]=100;		//starts the Spindle
				SpindleState= Running;
			}
			else
				{
					motor[Spindle]=0;		//stops the Spindle
					SpindleState=Stopped;
				}
			clearTimer(T1);
		}
	}

	if(BTN_ROTATESPINDLE_BACKWARD)
	{
		if(time1(T1)>500)	//checks to see if button isn't pressed to fast
		{
			if(SpindleState== Stopped)
			{
				motor[Spindle]=-100;		//starts the spindle (backwards)
				SpindleState= Running;
			}
			else
				{
					motor[Spindle]=0;		//stops the spindle
					SpindleState=Stopped;
				}
			clearTimer(T1);
		}
	}

	if(BTN_GATE_CTRL)
	{
		if(time1(T3)>500)	//checks to see if button is pressed too fast
		{
			if(GateState== Closed)
			{
				servo[Gate]= GATE_OPEN;	//opens gate
				GateState=Open;
			}
			else
			{
				servo[Gate]=GATE_CLOSED;	//closes gate
				GateState=Closed;
			}
			clearTimer(T3);
		}
	}

	if(BTN_LIFT_BASE)
	{
		moveLift(LIFT_BASE);
	}

	if(BTN_LIFT_LOWERGOAL)
	{
		moveLift(LIFT_LOWER);
	}

	if(BTN_LIFT_MIDDLEGOAL)
	{
		moveLift(LIFT_MIDDLE);
	}

	if(BTN_LIFT_TOPGOAL)
	{
		moveLift(LIFT_TOP);
	}

	if(BTN_GRAB_GOALBASE)
	{
		//blank for now
	}
}

void moveLift(int encoderCounts)
{
	//Blank for now
}
