#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by K^3S^3T Hogwarts wizards              !!*//

task main()
{
	while(true)
	{
		if(nNxtButtonPressed == 1)	// raises lift
		{
			motor[Lift] = 25;
		}
		if(nNxtButtonPressed == 2)	// lowers lift
		{
			motor[Lift] = -25;
		}
		if(nNxtButtonPressed == 3)	// stops lift
		{
			motor[Lift] = 0;
		}
	}
}
