#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     irseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheels,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Spindle,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightWheels,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    Gate,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//use header files from Xander's 3rd party robotc driver suite:
// https://github.com/botbench/robotcdriversuite/tree/master/include

//program assumes Sensor Multiplexor is connected to S4. msensor_S4_1, msensor_S4_2 etc refer to sensors connected off the MUX
// by port number.

//note the pragma that configures the MUX in the pragma section. Shown here as example.
//#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)

//ensure the SMUX battery pack is turned on for the run.
//ensure it is turned off afterward.

//>>Important
//remember to incorporate into diagnostic as well as tele-op and if neccessary Autonomous programs.



#include "hitechnic-sensormux.h"
#include "lego-touch.h"

const tMUXSensor TouchSensor1=msensor_S4_1;
const tMUXSensor TouchSensor2=msensor_S4_2;
const tMUXSensor TouchSensor3=msensor_S4_3;

task main()
{

//plays different tone, based on sensor pressed.

 while(1){
   if(TSreadState(TouchSensor1)){
     playTone(2000,2);
   }
   if(TSreadState(TouchSensor2)){
     playTone(5000,2);
   }
   if(TSreadState(TouchSensor3)){
     playTone(8000,2);
   }


 }
}
